export default {
  font_family:[
        {value:"'Abril Fatface', cursive",text:"Abril Fatface"},
        {value:"'Alegreya Sans', serif",text:"Alegreya Sans"},
        {value:"'Alice', serif",text:"Alice"},
        {value:"'Amaranth', sans-serif",text:"Amaranth"},
        {value:"'Anonymous Pro', monospace",text:"Anonymous Pro"},
        {value:"'Archivo Narrow', sans-serif",text:"Archivo Narrow"},
        {value:"'Arvo', serif",text:"Arvo"},
        {value:"'Average', serif",text:"Average"},
        {value:"'BioRhyme', serif",text:"BioRhyme"},
        {value:"'Bitter', serif",text:"Bitter"},
        {value:"'Bree Serif', serif",text:"Bree Serif"},

        {value:"'Cabin', sans-serif",text:"Cabin"},
        {value:"'Cantata One', serif",text:"Cantata One"},
        {value:"'Cardo', serif",text:"Cardo"},
        {value:"'Chivo', sans-serif",text:"Chivo"},
        {value:"'Cantarell', sans-serif",text:"Cantarell"},
        {value:"'Cantata One', serif",text:"Cantata One"},
        {value:"'Cardo', serif",text:"Cardo"},
        {value:"'Chivo', sans-serif",text:"Chivo"},
        {value:"'Crimson Text', serif",text:"Crimson Text"},
        {value:"'Dancing Script', cursive",text:"Dancing Script"},
        {value:"'Domine', serif",text:"Domine"},
        {value:"'EB Garamond', serif",text:"EB Garamond"},
        {value:"'Fira Sans', sans-serif",text:"Fira Sans"},
        {value:"'Fira Sans Condensed', sans-serif",text:"Fira Sans Condensed"},
        {value:"'Fjalla One', sans-serif",text:"Fjalla One"},
        {value:"'Gentium Book Basic', serif",text:"Gentium Book Basic"},
        {value:"'Hind', sans-serif",text:"Hind"},
        {value:"'Imprima', sans-serif",text:"Imprima"},
        {value:"'Istok Web', sans-serif",text:"Istok Web"},
        {value:"'Josefin Sans', sans-serif",text:"Josefin Sans"},
        {value:"'Karla', sans-serif",text:"Karla"},
        {value:"'Lato', sans-serif",text:"Lato"},
        {value:"Libre Baskerville', serif",text:"Libre Baskerville"},
        {value:"'Libre Franklin', sans-serif",text:"Libre Franklin"},
        {value:"'Lora', serif",text:"Lora"},
        {value:"'Merriweather', serif",text:"Merriweather"},
        {value:"'Montserrat', sans-serif",text:"Montserrat"},
        {value:"'Neuton', serif",text:"Neuton"},
        {value:"'Neuton', serif",text:"Neuton"},
        {value:"'Old Standard TT', serif",text:"Old Standard TT"},
        {value:"'Open Sans', sans-serif",text:"Open Sans"},
        {value:"'Oswald', sans-serif",text:"Oswald"},
        {value:"'PT Sans', sans-serif",text:"PT Sans"},
        {value:"'PT Serif', serif",text:"PT Serif"},
        {value:"'Playfair Display', serif",text:"Playfair Display"},
        {value:"'Playfair Display SC', serif",text:"Playfair Display SC"},
        {value:"'Poppins', sans-serif",text:"Poppins"},
        {value:"'Quattrocento', serif",text:"Quattrocento"},
        {value:"'Quattrocento Sans', sans-serif",text:"Quattrocento Sans"},
        {value:"'Questrial', sans-serif",text:"Questrial"},
        {value:"'Quicksand', sans-serif",text:"Quicksand"},
        {value:"'Rajdhani', sans-serif",text:"Rajdhani"},
        {value:"'Raleway', sans-serif",text:"Raleway"},
        {value:"'Roboto', sans-serif",text:"Roboto"},
        {value:"'Roboto Slab', serif",text:"Roboto Slab"},
        {value:"'Rokkitt', serif",text:"Rokkitt"},
        {value:"'Rubik', sans-serif",text:"Rubik"},
        {value:"'Rufina', serif",text:"Rufina"},
        {value:"'Sacramento', cursive",text:"Sacramento"},
        {value:"'Sintony', sans-serif",text:"Sintony"},
        {value:"'Source Sans Pro', sans-serif",text:"Source Sans Pro"},
        {value:"'Source Serif Pro', serif",text:"Source Serif Pro"},
        {value:"'Space Mono', monospace",text:"Space Mono"},

        {value:"''Titillium Web', sans-serif', monospace",text:"Titillium Web"},
        {value:"'Ubuntu', sans-serif",text:"Ubuntu"},
        {value:"'Ultra', serif",text:"Ultra"},
        {value:"'Vollkorn', serif",text:"Vollkorn"},
        {value:"'Work Sans', sans-serif",text:"Work Sans"},


    ],
  }